name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install WeasyPrint dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-cffi libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install weasyprint markdown

    - name: Convert Markdown to PDF
      run: |
        python3 ./md_to_pdf.py README.md Resume-Elias-Weston-Farber.pdf

    - name: Check for changes
      id: git_diff
      run: |
        git fetch
        git diff --exit-code || echo "PDF_changed=true" >> $GITHUB_ENV

    - name: Commit and push changes
      if: env.PDF_changed == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Resume-Elias-Weston-Farber.pdf
        git commit -m 'Update Resume-Elias-Weston-Farber.pdf'
        git push
